server {
    listen 80;
    server_name localhost 127.0.0.1;
    client_max_body_size 1m;
    access_log off;

    location / {
        proxy_pass http://web:3000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
