import { test, expect } from '@playwright/test';
const suffix=Date.now().toString();
for(const kind of ['individual','corporation'])test(kind+' create, persist, edit and delete',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'申請者管理画面',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'申請者を新規登録'}).click();
 if(kind==='corporation')await page.getByRole('radio',{name:'法人',exact:false}).check();
 const name=(kind==='individual'?'試験 太郎 ':'株式会社 試験 ')+suffix;
 await page.getByLabel(kind==='individual'?'氏名必須':'法人名必須',{exact:true}).fill(name);
 await page.getByLabel('フリガナ').fill('シケン タロウ');
 if(kind==='corporation'){
  await page.getByLabel('法人番号').fill(suffix.slice(-13).padStart(13,'9'));
  await page.getByLabel('代表者氏名').fill('試験 太郎');
 }
 await page.getByLabel('郵便番号').fill('100-0001');
 await page.getByLabel('市区町村').fill('千代田区');
 await page.getByLabel('町名・番地').fill('試験町1-2-3');
 await page.getByLabel('メールアドレス').fill('test@example.test');
 await page.getByLabel('電話番号').fill('03-1234-5678');
 await page.getByRole('button',{name:'確認画面へ進む'}).click();
 await expect(page.getByRole('button',{name:'この内容で登録'})).toBeDisabled();
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'この内容で登録'}).click();
 await expect(page.getByRole('heading',{name:'申請者を登録しました。',exact:true}).first()).toBeVisible();
 await page.getByRole('button',{name:'登録内容を確認'}).click();
 await expect(page.locator('main').getByText(name,{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'申請者情報を編集'}).click();
 await page.getByLabel('建物名・部屋番号').fill('更新ビル 202');
 await page.getByRole('button',{name:'確認画面へ進む'}).click();
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'この内容で更新'}).click();
 await page.reload();
 await page.getByRole('textbox',{name:'申請者を検索'}).fill(name);
 await page.getByRole('button',{name:name,exact:true}).click();
 await expect(page.getByText('更新ビル 202',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'削除する'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'キャンセル',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.getByRole('button',{name:'削除する'}).click();
 await page.getByRole('button',{name:'削除を確定'}).click();
 await expect(page.getByRole('status')).toContainText('削除しました');
 await expect(page.getByRole('button',{name:name,exact:true})).toHaveCount(0);
});
test('filter, empty state, isolation and mobile layout',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('button',{name:'山田 太郎',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'本文へ移動'}).focus();
 await page.keyboard.press('Enter');
 await expect(page.locator('#main')).toBeFocused();
 await page.getByLabel('申請者区分で絞り込み').selectOption('corporation');
 await expect(page.locator('tbody .badge.individual')).toHaveCount(0);
 await page.getByLabel('申請者を検索').fill('存在しない申請者');
 await expect(page.getByText('該当する申請者が見つかりません')).toBeVisible();
 await page.getByRole('button',{name:'検索条件をクリア'}).click();
 await page.getByLabel('デモ利用者',{exact:true}).selectOption('demo-b');
 await expect(page.getByText('申請者はまだ登録されていません')).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByLabel('デモ利用者',{exact:true}).selectOption('demo-a');
 await expect(page.getByRole('button',{name:'山田 太郎',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
